apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  slack_api_url: "https://hooks.slack.com/services/XXXXXXX/XXXXXXX/XXXXXXXXX"
