kind: Service
apiVersion: v1
metadata:
  name: node-app-svc
  namespace: dev-ns
  labels:
    app: app-1
    monitoring: enabled
spec:
  selector:
    app:  app-1
  type: ClusterIP
  ports:
  - name:  http-metrics
    port:  8080
    targetPort:  3000